#!/bin/bash
#
# Git hook script for å enforce conventional commits med påkrevd issueref
# dvs. enten jira- eller gitbub-issue-ref eller teksten "noref"

[[ -n "$DEBUG" ]] && set -x # turn -x on if DEBUG is set to a non-empty string

# echo "Sjekker commit-meldinger..."

COMMIT_CONVENTION_TYPES="build|chore|ci|docs|feat|fix|perf|refactor|revert|test"
COMMIT_CONVENTION_SEPARATOR=":"
COMMIT_CONVENTION_REGEX="^($COMMIT_CONVENTION_TYPES)([(][-_ a-zA-Z0-9]+[)]|)${COMMIT_CONVENTION_SEPARATOR} ?([A-Z]+-[0-9]+|#[0-9]+|noref) .+"
MERGE_REGEX="^Merge branch '.*' into "
# strip commit message of comments
INPUT_COMMIT_MESSAGE=$(sed -e "s/^#.*$//g" "$1")

# test against commit convention regex
if [[ $INPUT_COMMIT_MESSAGE =~ $COMMIT_CONVENTION_REGEX || $INPUT_COMMIT_MESSAGE =~ $MERGE_REGEX ]]; then
	# echo "OK"
	exit 0 # All good
else
        echo
		echo "ERROR: Commit-melding \"$INPUT_COMMIT_MESSAGE\" matcher ikke konvensjon."
        echo
		echo "Typer: $COMMIT_CONVENTION_TYPES"
		echo "Format: <type><(valgfritt scope)>: <issueref|noref> <commit message>"
		echo "Eksempler:"
		echo "    feat(cool stuff): PLAT-123 added a cool feature"
		echo "    fix(not so cool stuff): #42 removed silly bug"
		echo "    feat: noref trenger ikke jira"
        exit 1
fi
