#!/bin/bash
#
# Git hook script for å enforce conventional commits med påkrevd issueref
# dvs. enten jira- eller gitbub-issue-ref eller teksten "noref"

[[ -n "$DEBUG" ]] && set -x # turn -x on if DEBUG is set to a non-empty string

# echo "Sjekker commit-meldinger..."
COMMIT_CONVENTION_TYPES="(build|chore|ci|docs|feat|fix|perf|refactor|revert|test)"
COMMIT_SCOPE="(\\([a-zA-Z0-9 _-]+\\))?!?:"
COMMIT_REF="\\((#[0-9]+|noref|[A-Z]+-[0-9]+)\\)"
COMMIT_MSG=" .+ "
COMMIT_CONVENTION_REGEX="^${COMMIT_CONVENTION_TYPES}${COMMIT_SCOPE}${COMMIT_MSG}${COMMIT_REF}.*"
MERGE_REGEX="^Merge branch '.*' into "

# strip commit message of comments
INPUT_COMMIT_MESSAGE=$(sed -e "s/^#.*$//g" "$1")

# test against commit convention regex
if [[ $INPUT_COMMIT_MESSAGE =~ $COMMIT_CONVENTION_REGEX || $INPUT_COMMIT_MESSAGE =~ $MERGE_REGEX ]]; then
  # echo "OK"
  exit 0 # All good
else
  echo
  echo "ERROR: Commit-melding \"$INPUT_COMMIT_MESSAGE\" matcher ikke konvensjon."
  echo
  echo "Typer: $COMMIT_CONVENTION_TYPES"
  echo "Format: <type><(valgfritt scope)>: <commit message> (<issueref|noref>)"
  echo "Eksempler:"
  echo "    feat(cool stuff): added a cool feature (PLAT-123)"
  echo "    fix(not so cool stuff): removed silly bug (#42)"
  echo "    feat: Trenger ikke jira, men må være eksplisitt (noref)"
  exit 1
fi
